### ISSUE TITLE
example of usage of trained models to predict events on new data

### ISSUE THREAD

**Issue by tutubalinaev** [aistairc/DeepEventMine#4]
Could you please add an example of how to use trained models for prediction on a list of raw .txt documents? Thank you in advance

**Comment by trieuhl** [comment]
Hi. Thank you for your question. For the current version, if you follow the steps on the README, the model is able to predict on the six BioNLP shared tasks and MLEE. Specifically, after you run the preprocess.sh, the script will preprocess the data sets and you can see (in the generated /data/.. folder) that the test sets are somehow the same as what you want to run, which contain a list of raw .txt. 

One difference is that, these shared tasks provide gold entities for the test sets in the *.a1 files. However, my model can also predict without gold entity. I will update soon so that you can try.

Does this answer fit your question? Feel free to discuss.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by trieuhl** [comment]
Hi. I have updated the code to predict for raw text.

**Comment by tutubalinaev** [comment]
Hi, thank you, I will try to run your example next week and give feedback!

**Comment by trieuhl** [comment]
I have updated the code given PMID as input, so maybe you can try.
